name: go-action

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'main.go file path'
        required: false
        default: 'main.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4' # The Go version to download (if necessary) and use.

      - name: Run Go
        run: | 
          go version
          go run ${{ github.event.inputs.path }}
